version: '3'
services:
  nginx:
    build: .
    image: setine/nginx:1.0
    container_name: nginx-localhost
    volumes:
    - ../dist/nginx/html:/usr/share/nginx/html
    - ../dist/nginx/conf:/etc/nginx
    - ../dist/nginx/log:/var/log/nginx
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 10s
      retries: 3
    # links:
    # - app
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
