version: '3'
services:
  nginx:
    build: ./docker/nginx/localhost
    image: setine/nginx:1.0
    container_name: nginx-localhost
    # volumes:
    # - ./express/dist/static:/usr/share/nginx/html/static
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 10s
      retries: 3
    links:
    - app
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
  app:
    build: ./docker/app/localhost
    image: setine/app:1.0
    container_name: app-localhost
    # volumes:
    # - ./express/dist/static:/usr/share/nginx/html/static
    ports:
    - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m
      timeout: 10s
      retries: 3
